# pytest.ini
[pytest]

# test paths
testpaths = test 

# automatic asyncio mode for async tests => no need to add @pytest.mark.asyncio to every async test
asyncio_mode = auto 

# custom markers => filter tests with -m flag (e.g. pytest -m unit)
markers = 
    unit: Unit tests 
    integration: Integration tests 
    e2e: End-to-end tests     